apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: platform
  namespace: flux
spec:
  interval: 5m0s
  path: /tenants/platform
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-sync
  targetNamespace: flux
